export const statePages = [
  {
    slug: "georgia-mortgage-loan-officer",
    stateName: "Georgia",
    stateCode: "GA",
    title: "Georgia Mortgage Loan Officer",
    description: "Georgia mortgage loan officer for purchase, refinance, HELOC, FHA, VA, jumbo, and first-time buyer loans.",
    h1: "Georgia Mortgage Loan Officer for Purchase, Refinance, and HELOC Loans",
    primaryKeyword: "Georgia mortgage loan officer",
    secondaryKeywords: ["GA home purchase loans", "Georgia refinance mortgage"],
    localKeywords: ["Atlanta", "Alpharetta", "Marietta", "Savannah", "Augusta"],
    marketNote: "Georgia borrowers often balance fast-growing metro areas with suburban and rural property options.",
  },
  {
    slug: "florida-mortgage-loan-officer",
    stateName: "Florida",
    stateCode: "FL",
    title: "Florida Mortgage Loan Officer",
    description: "Florida mortgage loan officer for home purchase, refinance, FHA, VA, jumbo, HELOC, and investment property loans.",
    h1: "Florida Mortgage Loan Officer for Purchase and Refinance Options",
    primaryKeyword: "Florida mortgage loan officer",
    secondaryKeywords: ["FL FHA loans", "Florida home purchase loan"],
    localKeywords: ["Jacksonville", "Orlando", "Tampa", "Miami", "Fort Lauderdale"],
    marketNote: "Florida financing often requires careful planning around condos, insurance, second homes, and investment properties.",
  },
  {
    slug: "texas-mortgage-loan-officer",
    stateName: "Texas",
    stateCode: "TX",
    title: "Texas Mortgage Loan Officer",
    description: "Texas mortgage loan officer for purchase loans, refinance, HELOC, FHA, VA, jumbo, and first-time buyer programs.",
    h1: "Texas Mortgage Loan Officer for Home Buyers and Refinancing",
    primaryKeyword: "Texas mortgage loan officer",
    secondaryKeywords: ["TX refinance mortgage", "Texas jumbo loans"],
    localKeywords: ["Dallas", "Houston", "Austin", "San Antonio", "Fort Worth"],
    marketNote: "Texas borrowers need guidance on property taxes, homestead considerations, and cash-out refinance rules.",
  },
  {
    slug: "tennessee-mortgage-loan-officer",
    stateName: "Tennessee",
    stateCode: "TN",
    title: "Tennessee Mortgage Loan Officer",
    description: "Tennessee mortgage loan officer for purchase, refinance, FHA, VA, HELOC, jumbo, and first-time buyer loans.",
    h1: "Tennessee Mortgage Loan Officer for Purchase and Refinance Loans",
    primaryKeyword: "Tennessee mortgage loan officer",
    secondaryKeywords: ["TN home loans", "Tennessee first-time home buyer"],
    localKeywords: ["Nashville", "Memphis", "Knoxville", "Chattanooga", "Franklin"],
    marketNote: "Tennessee buyers often compare affordability, commute patterns, and growing job centers when choosing loan options.",
  },
  {
    slug: "north-carolina-mortgage-loan-officer",
    stateName: "North Carolina",
    stateCode: "NC",
    title: "North Carolina Mortgage Officer",
    description: "North Carolina mortgage loan officer for purchase, refinance, FHA, VA, HELOC, jumbo, and first-time buyer loans.",
    h1: "North Carolina Mortgage Loan Officer for Home Financing",
    primaryKeyword: "North Carolina mortgage loan officer",
    secondaryKeywords: ["NC purchase loans", "North Carolina refinance"],
    localKeywords: ["Charlotte", "Raleigh", "Durham", "Greensboro", "Wilmington"],
    marketNote: "North Carolina borrowers frequently compare urban, suburban, coastal, and investment property opportunities.",
  },
  {
    slug: "south-carolina-mortgage-loan-officer",
    stateName: "South Carolina",
    stateCode: "SC",
    title: "South Carolina Mortgage Officer",
    description: "South Carolina mortgage loan officer for purchase loans, refinance, FHA, VA, jumbo, HELOC, and first-time buyers.",
    h1: "South Carolina Mortgage Loan Officer for Buyers and Owners",
    primaryKeyword: "South Carolina mortgage loan officer",
    secondaryKeywords: ["SC mortgage refinance", "South Carolina FHA loans"],
    localKeywords: ["Charleston", "Columbia", "Greenville", "Myrtle Beach", "Spartanburg"],
    marketNote: "South Carolina financing may involve primary residences, coastal properties, new construction, and relocation buyers.",
  },
  {
    slug: "maryland-mortgage-loan-officer",
    stateName: "Maryland",
    stateCode: "MD",
    title: "Maryland Mortgage Loan Officer",
    description: "Maryland mortgage loan officer for purchase, refinance, HELOC, FHA, VA, jumbo, and first-time buyer financing.",
    h1: "Maryland Mortgage Loan Officer for Purchase, Refinance, and HELOC Loans",
    primaryKeyword: "Maryland mortgage loan officer",
    secondaryKeywords: ["MD purchase loans", "Maryland HELOC"],
    localKeywords: ["Baltimore", "Silver Spring", "Rockville", "Frederick", "Annapolis"],
    marketNote: "Maryland borrowers often evaluate commuter markets, county taxes, condo options, and home equity goals.",
  },
];

export const servicePages = [
  {
    slug: "home-purchase-loans",
    title: "Home Purchase Loans",
    description: "Home purchase loan guidance for first-time buyers, move-up buyers, FHA, VA, conventional, jumbo, and investment homes.",
    h1: "Home Purchase Loans for Buyers in GA, FL, TN, NC, SC, MD, and TX",
    primaryKeyword: "home purchase loans",
    secondaryKeywords: ["first-time home buyer loans", "mortgage preapproval"],
    serviceName: "home purchase loan",
    audience: "first-time buyers, move-up buyers, and relocating borrowers",
    benefits: ["preapproval planning", "down payment options", "purchase contract timelines"],
    loanTypes: ["Conventional", "FHA", "VA", "Jumbo"],
  },
  {
    slug: "mortgage-refinance",
    title: "Mortgage Refinance",
    description: "Refinance mortgage guidance for rate-and-term refinance, cash-out refinance, payment goals, and home equity planning.",
    h1: "Mortgage Refinance Options for Rate, Term, and Cash-Out Goals",
    primaryKeyword: "refinance mortgage",
    secondaryKeywords: ["rate-and-term refinance", "cash-out refinance"],
    serviceName: "mortgage refinance",
    audience: "homeowners reviewing rate, term, payment, and equity goals",
    benefits: ["payment review", "cash-out planning", "loan term comparisons"],
    loanTypes: ["Conventional", "FHA", "VA", "Jumbo"],
  },
  {
    slug: "heloc-loans",
    title: "HELOC Loans",
    description: "HELOC loan guidance for home equity lines of credit, renovations, debt planning, and flexible home equity financing.",
    h1: "HELOC Loans and Home Equity Line of Credit Guidance",
    primaryKeyword: "HELOC loans",
    secondaryKeywords: ["home equity line of credit", "home equity financing"],
    serviceName: "HELOC loan",
    audience: "homeowners who want flexible access to available home equity",
    benefits: ["renovation funding", "flexible draw options", "equity planning"],
    loanTypes: ["HELOC", "Home Equity Loan", "Cash-Out Refinance"],
  },
  {
    slug: "fha-loans",
    title: "FHA Loans",
    description: "FHA loan guidance for low down payment home buyers, flexible credit profiles, refinancing, and first-time buyers.",
    h1: "FHA Loans for Low Down Payment and Flexible Credit Needs",
    primaryKeyword: "FHA loans",
    secondaryKeywords: ["FHA mortgage loan officer", "low down payment mortgage"],
    serviceName: "FHA loan",
    audience: "borrowers seeking low down payment options or flexible credit guidelines",
    benefits: ["lower down payment paths", "flexible credit review", "first-time buyer planning"],
    loanTypes: ["FHA Purchase", "FHA Refinance", "FHA Streamline"],
  },
  {
    slug: "conventional-loans",
    title: "Conventional Loans",
    description: "Conventional loan guidance for purchase, refinance, first-time buyers, private mortgage insurance, and strong credit borrowers.",
    h1: "Conventional Loans for Purchase and Refinance Borrowers",
    primaryKeyword: "conventional loans",
    secondaryKeywords: ["conventional mortgage", "private mortgage insurance"],
    serviceName: "conventional loan",
    audience: "borrowers comparing agency loan options with flexible down payment choices",
    benefits: ["competitive pricing review", "PMI planning", "second home options"],
    loanTypes: ["Conventional Purchase", "Conventional Refinance", "High-Balance"],
  },
  {
    slug: "va-loans",
    title: "VA Loans",
    description: "VA loan guidance for eligible veterans, service members, surviving spouses, purchase loans, refinance, and VA benefits.",
    h1: "VA Loans for Eligible Veterans, Service Members, and Families",
    primaryKeyword: "VA loans",
    secondaryKeywords: ["VA mortgage", "veteran home loan"],
    serviceName: "VA loan",
    audience: "eligible veterans, service members, and surviving spouses",
    benefits: ["VA entitlement review", "zero down payment options", "VA refinance planning"],
    loanTypes: ["VA Purchase", "VA IRRRL", "VA Cash-Out"],
  },
  {
    slug: "jumbo-loans",
    title: "Jumbo Loans",
    description: "Jumbo loan guidance for high-value home purchases, refinance, complex income, asset review, and larger mortgage needs.",
    h1: "Jumbo Loans for High-Value Home Financing",
    primaryKeyword: "jumbo loans",
    secondaryKeywords: ["jumbo mortgage", "high-balance home loan"],
    serviceName: "jumbo loan",
    audience: "borrowers buying or refinancing homes above conforming loan limits",
    benefits: ["large loan structuring", "asset documentation review", "rate and reserve planning"],
    loanTypes: ["Jumbo Purchase", "Jumbo Refinance", "High-Balance"],
  },
  {
    slug: "investment-property-loans",
    title: "Investment Property Loans",
    description: "Investment property loan guidance for rental homes, refinance, investor financing, cash flow review, and portfolio goals.",
    h1: "Investment Property Loans for Rental and Portfolio Goals",
    primaryKeyword: "investment property loans",
    secondaryKeywords: ["rental property mortgage", "DSCR/investor financing overview"],
    serviceName: "investment property loan",
    audience: "real estate investors and buyers evaluating rental property financing",
    benefits: ["rental income review", "cash flow planning", "portfolio financing strategy"],
    loanTypes: ["Conventional Investment", "Jumbo Investment", "DSCR Overview"],
  },
];

export const homePage = {
  slug: "",
  title: "Srikanth Reddy Bollampalli | Mortgage Loan Officer",
  description: "Srikanth Reddy Bollampalli helps with purchase, refinance, HELOC, FHA, VA, jumbo, and first-time buyer loans in GA, FL, TN, NC, SC, MD, and TX.",
  h1: "Mortgage Loan Officer for Purchase, Refinance, and HELOC Loans in GA, FL, TN, NC, SC, MD, and TX",
  primaryKeyword: "mortgage loan officer GA FL TN NC SC MD TX",
  secondaryKeywords: ["purchase loans", "refinance mortgage", "HELOC loans"],
};
